# Generated by Django 5.1.7 on 2025-04-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Номер бонусной карты",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Баланс бонусной карты",
                    ),
                ),
                (
                    "bonus",
                    models.PositiveSmallIntegerField(
                        blank=True, default=5, null=True, verbose_name="Бонус"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=100,
                        verbose_name="Владелец бонусной карты",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        help_text="Введите дату своего рождения",
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("мужской", "мужской"), ("женский", "женский")],
                        help_text="Выберите пол",
                        verbose_name="Пол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бонусная карта",
                "verbose_name_plural": "Бонусные карты",
                "ordering": ["number"],
            },
        ),
    ]
