# Generated by Django 5.1.7 on 2025-04-09 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="phone_number",
            field=models.CharField(
                default=9999999999,
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате 9999999999 (10 цифр)",
                        regex="d{10}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
